"""Builds tf_native.dll: writes profile.h, the layout of the profile the companion makes for the installed game
(companion/game_profile.py: where the game's functions and structures are, read from the game's own PDB on the
player's PC after every game update), then compiles with Zig. The DLL itself fits every game version the profile can be
made for; it is built again only when its own code changes.

  py native/build.py

Needs: ziglang (pip install ziglang). Writes native/profile.h, native/build/ (the DLL and the fake-engine test DLL),
copies the DLL to TownfallCompanion/Scripts/tf_native.dll, and, with the game installed, writes its profile next to it
as the companion would (a few seconds, once after each game update).
"""
import shutil
import subprocess
import sys
from pathlib import Path

import ziglang

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
sys.path.insert(0, str(REPO / "TownfallCompanion" / "companion"))
import config  # noqa: E402
import game_profile  # noqa: E402

BUILD = ROOT / "build"
SHIPPED = REPO / "TownfallCompanion" / "Scripts" / "tf_native.dll"
SOURCE = "https://github.com/smaugikun/silent-hill-townfall-companion"


def header():
    """profile.h: game_profile.FIELDS as the C struct the DLL reads the profile into, a name for each value the DLL's
    code uses, and each function's RVA and first bytes, checked against the running game before anything is hooked."""
    lines = ["/* Generated by native/build.py from companion/game_profile.py's FIELDS: the layout of the profile the",
             " * companion writes for the installed game (Scripts/tf_native.profile), and the names the code uses. */",
             f"#define PROFILE_VERSION {game_profile.VERSION}u",
             "struct GameProfile {", "    char magic[8];", "    uint32_t version, size;"]
    for name, kind in game_profile.FIELDS:
        lines.append(f"    uint32_t {name};" if kind == "I" else f"    unsigned char {name}[{int(kind[:-1])}];")
    lines += ["};", f'_Static_assert(sizeof(struct GameProfile) == {game_profile.LAYOUT.size}, "game_profile.FIELDS");',
              "static struct GameProfile profile;"]
    lines += [f"#define {name.upper()} (profile.{name})" for name, kind in game_profile.FIELDS
              if kind == "I" and name not in ("timestamp", "image_size")]
    lines.append("static const struct { const uint32_t *rva; const unsigned char *code; } profile_code[] = {")
    lines += [f"    {{&profile.{name[:-5]}_rva, profile.{name}}},"
              for name, _ in game_profile.FIELDS if name.endswith("_code")]
    lines.append("};")
    return "\n".join(lines) + "\n"


def version_resource():
    """The DLL's version information, as Windows shows it under Properties > Details: what it is, whose, which
    version (config.VERSION), its license (the copyright line of LICENSE) and where its source is."""
    numbers = ",".join([*config.VERSION.split("."), "0"][:4])
    notice = next(line for line in (REPO / "LICENSE").read_text(encoding="utf-8").splitlines()
                  if line.startswith("Copyright"))  # "Copyright (c) 2026 smaugikun"
    strings = {
        "CompanyName": notice.split(" ", 3)[-1],
        "FileDescription": "Townfall Companion: the CRTV's picture and sound from the game, for the companion",
        "FileVersion": config.VERSION,
        "InternalName": "tf_native",
        "LegalCopyright": f"{notice}. MIT License.",
        "OriginalFilename": "tf_native.dll",
        "ProductName": "Townfall Companion",
        "ProductVersion": config.VERSION,
        "Comments": f"Open source: {SOURCE}",
    }
    values = "\n".join(f'      VALUE "{key}", "{value}"' for key, value in strings.items())
    return f"""1 VERSIONINFO
FILEVERSION {numbers}
PRODUCTVERSION {numbers}
FILEFLAGSMASK 0x3F
FILEFLAGS 0x0
FILEOS 0x40004
FILETYPE 0x2
FILESUBTYPE 0x0
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904B0"
    BEGIN
{values}
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x409, 1200
  END
END
"""


def compile_dll(source, output, *resources):
    vendor = ROOT / "vendor" / "minhook"
    # -s: no debug symbols, whose ID would carry where Zig keeps its build files: the same source gives the same DLL
    # wherever it is built.
    command = [str(Path(ziglang.__file__).parent / "zig.exe"), "cc", "-target", "x86_64-windows-gnu", "-std=c11", "-O2",
               "-s", "-shared", "-I", str(vendor / "include"), str(source),
               *(str(vendor / "src" / path) for path in ("buffer.c", "hook.c", "trampoline.c", "hde/hde64.c")),
               *(str(path) for path in resources), "-lole32", "-o", str(output)]
    subprocess.run(command, check=True, cwd=ROOT)


def main():
    (ROOT / "profile.h").write_text(header(), encoding="ascii", newline="\n")
    BUILD.mkdir(exist_ok=True)
    (BUILD / "version.rc").write_text(version_resource(), encoding="ascii", newline="\n")
    compile_dll(ROOT / "tf_native.c", BUILD / "tf_native.dll", BUILD / "version.rc")
    compile_dll(ROOT / "test_harness.c", BUILD / "tf_native_tests.dll")
    shutil.copy2(BUILD / "tf_native.dll", SHIPPED)
    print(f"Built {SHIPPED} and {BUILD / 'tf_native_tests.dll'} (fake-engine tests only, never installed)")
    game = config.find_game_dir()
    exe = game / game_profile.GAME_EXE if game else None
    if exe and exe.is_file() and game_profile.needed(exe):
        print(f"Reading {exe} and its PDB for its profile (a few seconds)...", flush=True)
        game_profile.write(exe)


if __name__ == "__main__":
    main()
