/* Generated by native/build.py from companion/game_profile.py's FIELDS: the layout of the profile the
 * companion writes for the installed game (Scripts/tf_native.profile), and the names the code uses. */
#define PROFILE_VERSION 1u
struct GameProfile {
    char magic[8];
    uint32_t version, size;
    uint32_t timestamp;
    uint32_t image_size;
    unsigned char identity[24];
    uint32_t get_resource_rva;
    unsigned char get_resource_code[16];
    uint32_t end_viewport_rva;
    unsigned char end_viewport_code[16];
    uint32_t transition_rva;
    unsigned char transition_code[16];
    uint32_t retain_texture_rva;
    unsigned char retain_texture_code[16];
    uint32_t readback_ctor_rva;
    unsigned char readback_ctor_code[16];
    uint32_t enqueue_copy_rva;
    unsigned char enqueue_copy_code[16];
    uint32_t lock_readback_rva;
    unsigned char lock_readback_code[16];
    uint32_t unlock_readback_rva;
    unsigned char unlock_readback_code[16];
    uint32_t poll_fence_rva;
    unsigned char poll_fence_code[16];
    uint32_t angle_2d_rva;
    unsigned char angle_2d_code[16];
    uint32_t radar_space_rva;
    unsigned char radar_space_code[16];
    uint32_t radar_update_rva;
    unsigned char radar_update_code[16];
    uint32_t capture_update_rva;
    unsigned char capture_update_code[16];
    uint32_t texture_rhi_offset;
    uint32_t extent_offset;
    uint32_t format_offset;
    uint32_t radio_active_offset;
    uint32_t radio_fine_tuning_offset;
    uint32_t radio_fine_state_offset;
    uint32_t radio_stage_offset;
    uint32_t radio_image_offset;
    uint32_t radio_capture_offset;
    uint32_t component_to_world_offset;
    uint32_t align_advanced;
    uint32_t align_stabilise;
    uint32_t align_rgb;
    uint32_t look_enemy_return_rva;
    uint32_t look_waypoint_return_rva;
    uint32_t executor_rva;
    uint32_t immediate_list_rva;
    uint32_t readback_size;
    uint32_t readback_fence_offset;
    uint32_t readback_mask_offset;
    uint32_t fence_pending_offset;
    uint32_t tracked_access_offset;
    uint32_t inside_pass_offset;
    uint32_t inside_pass_mask;
    uint32_t gpu_mask_offset;
    uint32_t executing_offset;
    uint32_t d3d12_texture_vtable_rva;
    uint32_t access_copy_src;
    uint32_t access_srv_mask;
    uint32_t transition_texture;
    uint32_t pixel_rgba8;
    uint32_t pixel_bgra8;
};
_Static_assert(sizeof(struct GameProfile) == 436, "game_profile.FIELDS");
static struct GameProfile profile;
#define GET_RESOURCE_RVA (profile.get_resource_rva)
#define END_VIEWPORT_RVA (profile.end_viewport_rva)
#define TRANSITION_RVA (profile.transition_rva)
#define RETAIN_TEXTURE_RVA (profile.retain_texture_rva)
#define READBACK_CTOR_RVA (profile.readback_ctor_rva)
#define ENQUEUE_COPY_RVA (profile.enqueue_copy_rva)
#define LOCK_READBACK_RVA (profile.lock_readback_rva)
#define UNLOCK_READBACK_RVA (profile.unlock_readback_rva)
#define POLL_FENCE_RVA (profile.poll_fence_rva)
#define ANGLE_2D_RVA (profile.angle_2d_rva)
#define RADAR_SPACE_RVA (profile.radar_space_rva)
#define RADAR_UPDATE_RVA (profile.radar_update_rva)
#define CAPTURE_UPDATE_RVA (profile.capture_update_rva)
#define TEXTURE_RHI_OFFSET (profile.texture_rhi_offset)
#define EXTENT_OFFSET (profile.extent_offset)
#define FORMAT_OFFSET (profile.format_offset)
#define RADIO_ACTIVE_OFFSET (profile.radio_active_offset)
#define RADIO_FINE_TUNING_OFFSET (profile.radio_fine_tuning_offset)
#define RADIO_FINE_STATE_OFFSET (profile.radio_fine_state_offset)
#define RADIO_STAGE_OFFSET (profile.radio_stage_offset)
#define RADIO_IMAGE_OFFSET (profile.radio_image_offset)
#define RADIO_CAPTURE_OFFSET (profile.radio_capture_offset)
#define COMPONENT_TO_WORLD_OFFSET (profile.component_to_world_offset)
#define ALIGN_ADVANCED (profile.align_advanced)
#define ALIGN_STABILISE (profile.align_stabilise)
#define ALIGN_RGB (profile.align_rgb)
#define LOOK_ENEMY_RETURN_RVA (profile.look_enemy_return_rva)
#define LOOK_WAYPOINT_RETURN_RVA (profile.look_waypoint_return_rva)
#define EXECUTOR_RVA (profile.executor_rva)
#define IMMEDIATE_LIST_RVA (profile.immediate_list_rva)
#define READBACK_SIZE (profile.readback_size)
#define READBACK_FENCE_OFFSET (profile.readback_fence_offset)
#define READBACK_MASK_OFFSET (profile.readback_mask_offset)
#define FENCE_PENDING_OFFSET (profile.fence_pending_offset)
#define TRACKED_ACCESS_OFFSET (profile.tracked_access_offset)
#define INSIDE_PASS_OFFSET (profile.inside_pass_offset)
#define INSIDE_PASS_MASK (profile.inside_pass_mask)
#define GPU_MASK_OFFSET (profile.gpu_mask_offset)
#define EXECUTING_OFFSET (profile.executing_offset)
#define D3D12_TEXTURE_VTABLE_RVA (profile.d3d12_texture_vtable_rva)
#define ACCESS_COPY_SRC (profile.access_copy_src)
#define ACCESS_SRV_MASK (profile.access_srv_mask)
#define TRANSITION_TEXTURE (profile.transition_texture)
#define PIXEL_RGBA8 (profile.pixel_rgba8)
#define PIXEL_BGRA8 (profile.pixel_bgra8)
static const struct { const uint32_t *rva; const unsigned char *code; } profile_code[] = {
    {&profile.get_resource_rva, profile.get_resource_code},
    {&profile.end_viewport_rva, profile.end_viewport_code},
    {&profile.transition_rva, profile.transition_code},
    {&profile.retain_texture_rva, profile.retain_texture_code},
    {&profile.readback_ctor_rva, profile.readback_ctor_code},
    {&profile.enqueue_copy_rva, profile.enqueue_copy_code},
    {&profile.lock_readback_rva, profile.lock_readback_code},
    {&profile.unlock_readback_rva, profile.unlock_readback_code},
    {&profile.poll_fence_rva, profile.poll_fence_code},
    {&profile.angle_2d_rva, profile.angle_2d_code},
    {&profile.radar_space_rva, profile.radar_space_code},
    {&profile.radar_update_rva, profile.radar_update_code},
    {&profile.capture_update_rva, profile.capture_update_code},
};
