"""Exports the CRTV artwork from the Photoshop file into TownfallCompanion/companion/static/crtv/ for the
phone UI: one PNG per part, plus layers.css placing each part where it sits in the PSD (in % of the
canvas), so nothing in the UI is measured by hand.

    pip install "psd-tools[composite]"
    python tools/export-crtv-layers.py <path to tv_final.psd>

Each part is rendered from its PSD layers the way Photoshop shows them: with every adjustment layer
above it (Hue/Saturation; one in a pass-through group reaches everything below it) and the Harmonize
smart objects. A harmonized button brings a square of the background around it, which would move
with the button, so a moving part is cut to its own layer's outline. The F key's recessed frame
belongs to the case and goes into the body; only its cap moves.

The page stacks the parts as the PSD does (static/index.html), the screen's picture under the CRT:
body, slider, CRT, scale, bezel, the needle and stations, the buttons, and the Panel glass on top.

The art is by smaugikun and ships with the mod (see THIRD_PARTY_NOTICES.md); the PSD itself isn't in the
repository.
"""
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageFilter
from psd_tools import PSDImage

OUT = Path(__file__).resolve().parents[1] / "TownfallCompanion" / "companion" / "static" / "crtv"

# part (file and CSS class) -> its PSD layers, and the layer whose outline it keeps.
PARTS = {
    "body": {"layers": ["Layer 0"]},                     # the TV, with holes for the screen and the dial
    "slider": {"layers": ["Layer 3", "Harmonized layer 2"], "shape": "Layer 3"},  # AV OUT / VIEW knob, at VIEW
    "crt": {"layers": ["CRT"]},                          # the picture tube's face, over the picture
    "scale": {"layers": ["scale"]},                      # the strip the needle runs along
    "bezel": {"layers": ["Layer 2"]},                    # frame around the screen with the channel numbers
    "key-f": {"layers": ["Layer 12", "Harmonized layer"], "shape": "Layer 12"},  # the F key, cap only (see above)
    "tune-up": {"layers": ["Layer 11", "Harmonized layer 3"], "shape": "Layer 11"},  # TUNING ▶
    "tune-down": {"layers": ["Layer 11 copy"]},          # TUNING ◀
    "panel": {"layers": ["Panel"]},                      # the glass over the screen and the scale
}


# Photoshop's adjustment layers (psd-tools layer kinds): each one changes everything below it.
ADJUSTMENTS = {"brightnesscontrast", "levels", "curves", "exposure", "vibrance", "huesaturation", "colorbalance",
               "blackandwhite", "photofilter", "channelmixer", "colorlookup", "invert", "posterize", "threshold",
               "selectivecolor", "gradientmap"}


def render(psd, names):
    """The named layers, with the groups holding them and the adjustments above them, composited on
    the full canvas."""
    layers = list(psd.descendants())  # bottom to top
    chosen = [layer for layer in layers if layer.name in names]
    missing = set(names) - {layer.name for layer in chosen}
    if missing:
        sys.exit(f"layers not found in the PSD: {', '.join(sorted(missing))} (PARTS maps PSD layer names)")
    top = max(layers.index(layer) for layer in chosen)
    chosen += [layer for layer in layers[top + 1:] if layer.is_visible() and layer.kind in ADJUSTMENTS]
    keep = set()
    for layer in chosen:
        while layer is not None and layer is not psd:
            keep.add(id(layer))
            layer = layer.parent
    return psd.composite(layer_filter=lambda layer: id(layer) in keep).convert("RGBA")


def cap_box(key):
    """The key's cap: the light square in the dark recess (its letter lies inside the box). Eroding
    first drops the light specks in the rust; the box then grows back by as much."""
    light = key.convert("L").point(lambda v: 255 if v > 150 else 0)
    solid = key.getchannel("A").point(lambda v: 255 if v > 200 else 0)
    left, top, right, bottom = ImageChops.darker(light, solid).filter(ImageFilter.MinFilter(5)).getbbox()
    return left - 2, top - 2, right + 2, bottom + 2


def main(psd_path):
    psd = PSDImage.open(psd_path)
    images = {}
    for part, spec in PARTS.items():
        image = render(psd, spec["layers"])
        if "shape" in spec:
            image.putalpha(ImageChops.darker(image.getchannel("A"), render(psd, [spec["shape"]]).getchannel("A")))
        images[part] = image

    key = images["key-f"]
    box = cap_box(key)
    well = key.copy()
    well.paste((0, 0, 0, 0), box)
    images["body"].alpha_composite(well)
    images["key-f"] = Image.new("RGBA", key.size)
    images["key-f"].paste(key.crop(box), box[:2])

    OUT.mkdir(parents=True, exist_ok=True)
    css = [f"/* Generated by tools/export-crtv-layers.py from {Path(psd_path).name} "
           f"({psd.width}x{psd.height}); don't edit by hand. */"]
    for part, image in images.items():
        left, top, right, bottom = image.getchannel("A").getbbox()
        image.crop((left, top, right, bottom)).save(OUT / f"{part}.png", optimize=True)
        css.append(f".crtv .part.{part} {{ left: {100 * left / psd.width:.3f}%; top: {100 * top / psd.height:.3f}%; "
                   f"width: {100 * (right - left) / psd.width:.3f}%; height: {100 * (bottom - top) / psd.height:.3f}%; }}")
        print(f"{part:10} box {left},{top} - {right},{bottom}")
    (OUT / "layers.css").write_text("\n".join(css) + "\n", encoding="utf-8")
    print(f"wrote {len(images)} parts and layers.css to {OUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
